package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// AddrTambon represents a row from 'spc_holding.addr_tambon'.
type AddrTambon struct {
	IDAddrTambon  sql.NullInt64  `json:"id_addr_tambon"`  // id_addr_tambon
	ZipCode       sql.NullInt64  `json:"zip_code"`        // zip_code
	TamNameTh     sql.NullString `json:"tam_name_th"`     // tam_name_th
	TamNameEn     sql.NullString `json:"tam_name_en"`     // tam_name_en
	IDAddrAmphure sql.NullInt64  `json:"id_addr_amphure"` // id_addr_amphure
	CreatedTime   sql.NullString `json:"created_time"`    // created_time
	UpdatedTime   sql.NullString `json:"updated_time"`    // updated_time
	DeletedTime   sql.NullString `json:"deleted_time"`    // deleted_time
}
