package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// AddrProvince represents a row from 'spc_holding.addr_province'.
type AddrProvince struct {
	IDAddrProvince    sql.NullInt64  `json:"id_addr_province"`    // id_addr_province
	ProvNameTh        sql.NullString `json:"prov_name_th"`        // prov_name_th
	ProvNameEn        sql.NullString `json:"prov_name_en"`        // prov_name_en
	IDAddrGeographies sql.NullInt64  `json:"id_addr_geographies"` // id_addr_geographies
	CreateTime        sql.NullString `json:"create_time"`         // create_time
	UpdateTime        sql.NullString `json:"update_time"`         // update_time
	DeletedTime       sql.NullString `json:"deleted_time"`        // deleted_time
}
