package models

// Code generated by xo. DO NOT EDIT.

// AddrGeography represents a row from 'spc_holding.addr_geographies'.
type AddrGeography struct {
	IDAddrGeographies *int  `json:"id_addr_geographies" db:"id_addr_geographies"` // id_addr_geographies
	GeoName           *string `json:"geo_name" db:"geo_name"`            // geo_name
}